export const environment = {
  JSONServerBaseURL: 'http://localhost:3000',
  locations: [
    'Ariyalur',
    'Chennai',
    'Coimbatore',
    'Cuddalore',
    'Dharmapuri',
    'Dindigul',
    'Erode',
    'Kancheepuram',
    'Kanyakumari',
    'Karur',
    'Krishnagiri',
    'Madurai',
    'Nagapattinam',
    'Namakkal',
    'Perambalur',
    'Pudukottai',
    'Ramanathapuram',
    'Selam',
    'Sivaganga',
    'Thanjavur',
    'The Nilgiris',
    'Theni',
    'Thiruvallur',
    'Thiruvannamalai',
    'Thirunelveli',
    'Tiruppur',
    'Trichirappalli',
    'Tuticorin',
    'Vellore',
    'Villupuram',
    'Virudhunagar',
  ],
};
